[package]
name = "dioxus-html-rsx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.20"
syn = {version = "1.0.98", features = ["full"]}

[dev-dependencies]
dioxus = { version = "0.2.4", features = ["desktop"] }
